# -*- coding: utf-8 -*-
"""task5.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19istk4c1C0W_vRG6-4Y-pAZ9XQjNjSuE
"""

#Task5
#Python code to calculate the sum of even numbers and sum of odd numbers from a list
# Get input from the user
input_list_str = input("Enter a list of numbers separated by spaces: ")

# Convert the input string to a list of integers
try:
  l = [int(x) for x in input_list_str.split()]

  # Initialize sums
  sum_even = 0
  sum_odd = 0

  # Iterate through the list and sum even and odd numbers
  for number in l:
    if number % 2 == 0:
      sum_even += number
    else:
      sum_odd += number

  # Print the results
  print(f"Sum of even numbers: {sum_even}")
  print(f"Sum of odd numbers: {sum_odd}")

except ValueError:
  print("Invalid input. Please enter numbers separated by spaces.")