# -*- coding: utf-8 -*-
"""task1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_tOtGCa9dIrMKk47XLuFNm6jbwGLL4K
"""

#Task1
#function that reads a CSV file and calculates mean, min, max.
import pandas as pd

def analyze_csv(file_url):
    """
    Reads a CSV/Excel file from a URL and calculates mean, min, and max
    for all numeric columns automatically.
    """
    # Try reading as CSV; if it fails, try as Excel
    try:
        df = pd.read_csv(file_url)
    except Exception:
        df = pd.read_excel(file_url)

    # Confirm successful load
    print("✅ CSV File Loaded Successfully!")
    print(df.head(), "\n")

    # Select only numeric columns
    numeric_cols = df.select_dtypes(include='number').columns

    if len(numeric_cols) == 0:
        print("❌ No numeric columns found in the file.")
        return None

    # Calculate statistics for each numeric column
    for col in numeric_cols:
        mean_val = df[col].mean()
        min_val = df[col].min()
        max_val = df[col].max()

        # Display results
        print(f"📊 Statistics for '{col}':")
        print(f"Mean: {mean_val}")
        print(f"Minimum: {min_val}")
        print(f"Maximum: {max_val}\n")

    # Create and return summary dictionary
    result = {
        col: {"mean": df[col].mean(), "min": df[col].min(), "max": df[col].max()}
        for col in numeric_cols
    }
    print(result)
    return result


# --- Example usage ---
# 👇 Just replace this with your own link (can be a CSV or Excel file)
file_url = "/content/drive/MyDrive/AIAP/Lab_2/Task1_Excel.xlsx"

# Call the function (no need to provide column name)
result = analyze_csv(file_url)