# -*- coding: utf-8 -*-
"""task2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EoaSPfSXlAys6uge--UGHA-wxZfKRG8c
"""

#Task2
# Function to check if a string is a palindrome
def is_palindrome(text):
  """Checks if a string is a palindrome (reads the same forwards and backwards, ignoring case and spaces).

  Args:
    text: The input string.

  Returns:
    True if the string is a palindrome, False otherwise.
  """
  # Convert to lowercase and remove spaces
  cleaned_text = "".join(char.lower() for char in text if char.isalnum())
  return cleaned_text == cleaned_text[::-1]

# Example usage:
print(is_palindrome("Racecar"))
print(is_palindrome("Madam, I'm Adam"))
print(is_palindrome("Hello world"))