# -*- coding: utf-8 -*-
"""task3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZXBO_hu2fTbcFAiujIRwya_oW27cGS8
"""

#Task3
import math # Imports the math module to use mathematical functions like pi.

def calculate_area(shape, **kwargs): # Defines a function named calculate_area that takes 'shape' as a string and a variable number of keyword arguments (**kwargs) for dimensions.
  """Calculates the area of various shapes. # Docstring: explains what the function does.

  Args: # Docstring section: describes the arguments the function takes.
    shape: The name of the shape (e.g., "circle", "rectangle", "triangle"). # Describes the 'shape' argument.
    **kwargs: Keyword arguments for the shape's dimensions. # Describes the **kwargs argument.

  Returns: # Docstring section: describes what the function returns.
    The area of the shape, or None if the shape is not supported or # Describes the return value.
    dimensions are missing.
  """
  if shape == "circle": # Checks if the shape is "circle".
    radius = kwargs.get("radius") # Gets the value for the 'radius' keyword argument. Returns None if 'radius' is not provided.
    if radius is not None: # Checks if 'radius' was provided (is not None).
      return math.pi * radius**2 # Calculates and returns the area of a circle (pi * radius squared).
    else: # If 'radius' was not provided.
      print("Error: Radius is required for a circle.") # Prints an error message.
      return None # Returns None indicating an error.
  elif shape == "rectangle": # Checks if the shape is "rectangle".
    length = kwargs.get("length") # Gets the value for the 'length' keyword argument.
    width = kwargs.get("width") # Gets the value for the 'width' keyword argument.
    if length is not None and width is not None: # Checks if both 'length' and 'width' were provided.
      return length * width # Calculates and returns the area of a rectangle (length * width).
    else: # If 'length' or 'width' was not provided.
      print("Error: Length and width are required for a rectangle.") # Prints an error message.
      return None # Returns None indicating an error.
  elif shape == "triangle": # Checks if the shape is "triangle".
    base = kwargs.get("base") # Gets the value for the 'base' keyword argument.
    height = kwargs.get("height") # Gets the value for the 'height' keyword argument.
    if base is not None and height is not None: # Checks if both 'base' and 'height' were provided.
      return 0.5 * base * height # Calculates and returns the area of a triangle (0.5 * base * height).
    else: # If 'base' or 'height' was not provided.
      print("Error: Base and height are required for a triangle.") # Prints an error message.
      return None # Returns None indicating an error.
  else: # If the shape is not "circle", "rectangle", or "triangle".
    print(f"Error: Shape '{shape}' is not supported.") # Prints an error message indicating the shape is not supported.
    return None # Returns None indicating an error.

# Example Usage: # Comment indicating the start of example usage.
print(f"Area of circle with radius 5: {calculate_area('circle', radius=5)}") # Calls the function for a circle with radius 5 and prints the result.
print(f"Area of rectangle with length 4 and width 6: {calculate_area('rectangle', length=4, width=6)}") # Calls the function for a rectangle and prints the result.
print(f"Area of triangle with base 3 and height 7: {calculate_area('triangle', base=3, height=7)}") # Calls the function for a triangle and prints the result.
print(f"Area of square with side 4: {calculate_area('square', side=4)}") # Calls the function for an unsupported shape ("square") and prints the result (will print an error message and None).
print(f"Area of circle without radius: {calculate_area('circle')}") # Calls the function for a circle without providing the required 'radius' and prints the result (will print an error message and None).